name: dev_test_build
on:
  # This workflow is automatically triggered upon a push request to the development branch. 
  # The test_build : indicating whether your code commits are not breaking during compilation.
  # The code_scan : indicating whether your code commits are not violating code scan rules.
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/**'
      - 'public/**'
      - 'README.md' 
      - 'sonar-project.properties'
  workflow_dispatch:   # Allow manual triggering

jobs:
  test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]     
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with: 
          ref: dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
  code_scan:
    needs: test_build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Analyze on SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}     
  uat_deploy:
    needs: test_build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with: 
          ref: dev
      - name: Use Node.js 21.x
        uses: actions/setup-node@v4
        with:
          node-version: '21.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: ls -R build
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages-uat
          folder: build 
      - name: List Contents of build Directory
        run: ls -R build
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: github_pages
          path: build
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
        with:
           timeout: 300000  # Time to timeout and cancel the deployment (5 minutes)
      - run: echo ${{ steps.deployment.outputs.page_url }}



