name: dev_test_build
on:
  # This workflow is automatically triggered upon a push request to the development branch. 
  # The test_build : indicating whether your code commits are not breaking during compilation.
  # The code_scan : indicating whether your code commits are not violating code scan rules.
  push:
    branches:
      - dev
    paths-ignore:
      - '.github/**'
      - 'public/**'
      - 'README.md' 
      - 'sonar-project.properties'
  workflow_dispatch:   # Allow manual triggering
  

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  test_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x]     
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with: 
          ref: dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
      
      
      #- name: List Contents of build Directory
      #  run: ls -R build
      #- name: Upload artifact
      #  uses: actions/upload-artifact@v4
      #  with:
      #    name: github_pages
      #    path: build



  uat_deploy:
    #environment:
    #  name: gh-pages-uat
    #  url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - name: Checkout Source Codes
        uses: actions/checkout@v4
        with: 
          ref: dev
      #- name: Download artifact
      #  uses: actions/download-artifact@v4
      #  with:
      #    name: github_pages
      #    path: github_pages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - run: ls -R build
      - name: Deploy to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_TOKEN }}
          branch: gh-pages-uat
          folder: build
